name: "lstm_combo"
checkpoint_dir: "/ais/gobi3/u/emansim/unsupervised-videos/models"
print_after: 100
display_after: 0
validate_after: 500
save_after: 500
max_iters: 10000000
dec_seq_length: 10
future_seq_length: 10
dec_conditional: true
future_conditional: true
binary_data: true
lstm {
  name: "lstm_1_enc"
  num_hid: 2048
  has_input: true
  input_dims: 4096
  w_dense {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_enc:w_dense"
    scale: 0.01
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  w_diag {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_enc:w_diag"
    scale: 0.1
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  b {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_enc:b"
    scale: 0.0
    epsilon: 0.0001
    momentum: 0.9
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  w_input {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_enc:w_input"
    scale: 0.01
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
}

lstm_dec {
  name: "lstm_1_dec"
  num_hid: 2048
  has_output: true
  has_input: true
  output_dims: 4096
  input_dims: 4096
  w_dense {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_dec:w_dense"
    scale: 0.01
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  w_diag {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_dec:w_diag"
    scale: 0.1
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  b {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_dec:b"
    scale: 0.0
    epsilon: 0.0001
    momentum: 0.9
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
   w_input {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_dec:w_input"
    scale: 0.01
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }

  w_output {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_dec:w_output"
    scale: 0.01
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  b_output {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_dec:b_output"
    scale: 0.0
    epsilon: 0.0001
    momentum: 0.9
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
}

lstm_future {
  name: "lstm_1_fut"
  num_hid: 2048
  has_output: true
  has_input: true
  input_dims: 4096
  output_dims: 4096
  w_dense {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_fut:w_dense"
    scale: 0.01
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  w_diag {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_fut:w_diag"
    scale: 0.1
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  b {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_fut:b"
    scale: 0.0
    epsilon: 0.0001
    momentum: 0.9
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  w_input {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_fut:w_input"
    scale: 0.01
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  w_output {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_fut:w_output"
    scale: 0.01
    epsilon: 0.0001
    momentum: 0.9
    l2_decay: 0.0001
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
  b_output {
    init_type: PRETRAINED
    file_name: "/ais/gobi3/u/emansim/unsupervised-videos/models/lstm_autoencoder_20151230175240.h5"
    dataset_name: "lstm_1_fut:b_output"
    scale: 0.0
    epsilon: 0.0001
    momentum: 0.9
    gradient_clip: 0.0001
    eps_decay_factor: 0.9
    eps_decay_after: 10000
  }
}
